version: '3'
services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    environment:
      DOCKER_HOST: tcp://docker:2375
      # list of vscode extensions to load before other extensions
      PRELOAD_EXTENSIONS: "arrterian.nix-env-selector"
      #DIRENV_LOG_FORMAT: ""
    volumes:
      - ..:/workspace:cached
      - nix:/nix
    security_opt:
      - label:disable

  docker:
    image: docker:dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_DRIVER: overlay2
    privileged: true
    volumes:
      - ..:/workspace:cached
      - docker:/var/lib/docker
    security_opt:
      - label:disable

volumes:
  nix:
  docker:
